let complete_log = document.getElementById("complete_log"),
public_log = document.getElementById("public_log"),
reset = document.getElementById("reset"),
firstname = document.getElementById("firstname"),
lastname = document.getElementById("lastname"),
phone_number = document.getElementById("phone_number"),
alt_phone_number = document.getElementById("alt_phone_number"),
email_address = document.getElementById("email_address"),
physical_address = document.getElementById("physical_address"),
acp = document.getElementById("acp"),
serviceExpress = document.getElementById("serviceExpress"),
ppid = document.getElementById("ppid"),
customer_issue = document.getElementById("customer_issue"),
probing = document.getElementById("probing"),
troubleshooting = document.getElementById("troubleshooting"),
resolution = document.getElementById("resolution"),
oracle = document.getElementById("oracle"),
bttr = document.getElementById("bttr"),
timezone = document.getElementById("timezone"),
hdd_data_loss = document.getElementById("hdd_data_loss"),
tarp = document.getElementById("tarp"),
vdi = document.getElementById("vdi"),
cidar = document.getElementById("cidar"),
sms_offered = document.getElementById("sms_offered"),
fru_to_cru = document.getElementById("fru_to_cru"),
cru_to_fru = document.getElementById("cru_to_fru"),
test_email = document.getElementById("test_email"),
one_ad_per_year = document.getElementById("one_ad_per_year"),
form_item = document.querySelectorAll(".form_item"),
blank_text_area = document.getElementById("blank_text_area"),
form_wrap = document.querySelectorAll("form.form-wrapper"),
context_menu = document.querySelector(".context_menu"),
menu_complete = document.querySelector(".menu_complete"),
menu_public = document.querySelector(".menu_public"),
menu_reset = document.querySelector(".menu_reset"),
menu_cut = document.querySelector(".menu_cut"),
menu_copy = document.querySelector(".menu_copy"),
menu_paste = document.querySelector(".menu_paste"),
tempElement;



